### ISSUE TITLE
[BUG] xAxis label too long causes radar chart cannot render correctly

### ISSUE THREAD

**Issue by liuxuan30** [danielgindi/ios-charts#205] opened 2015-07-11 05:29 UTC
By accident I see my data source feed a very long string, about 4xx width, and this causes the radar chart cannot draw itself.

I have managed to limit the width through hard code (not finding a good place to hold the variable):
```Swift
        _xAxis.labelWidth = widthText.sizeWithAttributes([NSFontAttributeName: _xAxis.labelFont]).width;
        
        if (_xAxis.labelWidth > 100)
        {
            _xAxis.labelWidth = 100
        }
        
        _xAxis.labelHeight = _xAxis.labelFont.lineHeight;
        _xAxis.values = xValues;
```
However, this limit the size, but when rendering, it still draw the whole text. Is there any way to render the text only within the rect? Tried to find a API, but no good.

This is the chart after I have set the width up to 100: 
![labeltoolong](https://cloud.githubusercontent.com/assets/4375169/8632508/d363f5a8-27d0-11e5-8154-efd18c2fd50e.png)

**Comment by davecom** [comment] 2015-07-19 20:13
I'm seeing this too - Basically if you have a label that's longer than a certain number of characters (haven't tested exactly, but it's <20 so not that long) the chart becomes tiny.

**Comment by liuxuan30** [comment] 2015-07-20 01:38
Yes, this is a defect because it need take the radius and label width into account while calculating. The idea is to show all the labels and chart. I am suggesting add a limit for the label width, and once it exceeds, it will render the text like "ABCD..."

I am having trouble to implement this, becuase the drawText function don't cut the width

**Comment by danielgindi** [comment] 2015-08-12 07:35
This, too, is a duplicate of #153. Please merge the discussions :-)

**Comment by danielgindi** [comment] 2015-08-12 07:35
I'm just trying to track the bugs and it makes it harder to try to understand the same bug twice...

**Closed by danielgindi** 2015-08-12 07:35 UTC
