### ISSUE TITLE
Animated moveViewToX()

### ISSUE THREAD

**Issue by tomastiminskas** [danielgindi/ios-charts#318] opened 2015-08-25 19:16 UTC
I think it's not an issue but I couldn't find a solution so maybe you can help me. 

I implemented ios-charts on a swift application I am working on and composed a graph to show some information. The graph has set setVisibleXRangeMaximum(9.0) but has more than 30 values, so the user can scroll on the graph.

I could center the selected bar on the screen when the user tap on some of the graph bars, but I can't animate it. I am using moveViewToX() method to move to an specific index. Is there a way to do the same as "moveViewToX()" does but animated?

**Comment by danielgindi** [comment] 2015-08-27 12:13
Duplicate #189

**Comment by danielgindi** [comment] 2015-08-27 12:13
I thought that this was a duplicate of #189, but it's a different kind of animation. It should actually be pretty easy to implement

**Comment by tomastiminskas** [comment] 2015-08-27 12:19
Thanks a lot Daniel. Waiting for the implementation of moveViewToX() with animation.

**Comment by tomastiminskas** [comment] 2015-09-11 15:40
Daniel, have you been able to add this feature to the library? Thanks in advance

**Comment by kexoth** [comment] 2015-10-26 22:47
:+1:

**Comment by idenjoe** [comment] 2016-02-19 08:07
Are you planning to add this feature soon?? Thanks.

**Closed** 2016-02-27 19:47 UTC
Labels: feature

**Comment by liuxuan30** [comment] 2016-02-29 01:40
really this is carried out :)
