### ISSUE TITLE
[CombinedChart] Grouped Bars + line chart

### ISSUE THREAD

**Issue by liuxuan30** [danielgindi/ios-charts#252] opened 2015-07-29 01:55 UTC
Looks like we don't support grouped bars + line chart tegother? 

Say I have 3 bars on each xIndex, but only one line dot on each xIndex.

**Comment by danielgindi** [comment] 2015-07-29 13:46
https://github.com/PhilJay/MPAndroidChart/issues/449

**Comment by liuxuan30** [comment] 2015-08-04 03:08
I was thinking to assemble the bar chart views and line chart views together as sub views, and then I was thinking only using renderers, and you actually implement it this way. The question is the matrix seems not correct? Can you point out where the matrix goes wrong? I am trying to fix it right now.

**Comment by danielgindi** [comment] 2015-08-12 07:32
Btw this is a duplicate of #169 :-) Closing...

**Closed by danielgindi** 2015-08-12 07:32 UTC
