### ISSUE TITLE
App/Xcode crashing when charts are loaded

### ISSUE THREAD

**Issue by BrandonShega** [danielgindi/ios-charts#410] opened 2015-09-23 15:42 UTC
We recently updated our app for Xcode 7 and the latest iOS Charts on Swift 2.0 and every time our app loads, it crashes and then Xcode crashes.

The error message that we are receiving is
```
Can not cast value of type 'Charts.ChartDataEntry' (0x1063ba290) to 'Charts.BarChartDataEntry' (0x1063be5b0).
```

This is on line 134 in the BarChartDataEntry.swift file.

Any insight would be greatly appreciated.

**Comment by liuxuan30** [comment] 2015-09-24 03:35
Have you checked do you feed wrong dataEntry? It looks like you add ChartDataEntry object but it should be BarChartDataEntry

**Comment by BrandonShega** [comment] 2015-09-24 13:31
We didn't change anything except the version of Xcode, our app is already on the store working and then we wanted to make it Xcode 7 compatible and it just dies now.

**Comment by liuxuan30** [comment] 2015-09-25 02:08
Then you need to debug or provide more info here... I am still thinking it's wrong data entry class you used. Have you tried the latest master branch? It's been upgraded for swift 2.0

**Comment by BrandonShega** [comment] 2015-09-25 12:54
Yes, after we upgraded to the latest charts and the new version of Xcode, everything went haywire.  I don't understand why it would start breaking now when we've had an app on the App Store for about 3 weeks that's worked perfectly fine.

**Comment by davidck** [comment] 2015-09-25 17:22
I ran into the exact same issue.

**Comment by liuxuan30** [comment] 2015-09-28 02:06
@BrandonShega and @davidck, we need more info and logs, and maybe the steps to reproduce it. You are welcome to debug more, since the error message gives you hint.

**Comment by BrandonShega** [comment] 2015-09-28 13:50
@liuxuan30 It looks like it's crashing when we make an array by copying the items of another array.  For example we have our array of BarChartDataEntry items and we make a copy of it:

```objc
NSMutableArray *currentDataCopy = [[NSMutableArray alloc] initWithArray:self.dashboardItem.currentGraphData copyItems:YES];
```

Which is then calling
```swift
public override func copyWithZone(zone: NSZone) -> AnyObject {}
```

and this is the method that is crashing and we get the error above in the console about casting.

Any help is greatly appreciated!

@davidck Is this what you are doing as well?

**Comment by davidck** [comment] 2015-09-28 14:06
@BrandonShega I've solved it temporarily by removing lines of codes from the Swift to Obj-C bridging headers.  In the generated Swift file, it seems it's holding duplicated references.  After removing them, it worked, however, if I rebuild the source, the issue will happen again due to the file being wrongly generated.  The issue can be about a mixture of my setup due to my Obj-C project with Cocoapods installed mix with a direct inclusion of the ios-charts framework directly into my project.

**Comment by BrandonShega** [comment] 2015-09-28 14:08
We solved it temporarily by not making copies of the data, maybe these are unrelated issues.

**Comment by liuxuan30** [comment] 2015-09-30 01:02
@BrandonShega seems you are closing to the root cause, you may need to provide a custom copyWithZone function, I am thinking if the ChartEntry needs one.

**Closed** 2015-10-01 15:50 UTC
